site_name: CARLA Simulator
repo_url: https://github.com/carla-simulator/carla
docs_dir: Docs
edit_uri: 'edit/master/Docs/'
theme: readthedocs
extra_css: [extra.css]

nav:
- Home: 'index.md'
- Getting started:
  - 'Introduction': 'start_introduction.md'
  - 'Quickstart installation': 'start_quickstart.md'
- Building CARLA:
  - 'Linux build': 'build_linux.md'
  - 'Windows build': 'build_windows.md'
  - 'Update CARLA': 'build_update.md'
  - 'Build system': 'build_system.md'
  - 'Running in a Docker': 'build_docker.md'
  - 'F.A.Q.': 'build_faq.md'
- First steps:
  - 'Core concepts': 'core_concepts.md'
  - '1st. World and client': 'core_world.md'
  - '2nd. Actors and blueprints': 'core_actors.md'
  - '3rd. Maps and navigation': 'core_map.md'
  - '4th. Sensors and data': 'core_sensors.md'
- Advanced steps:
  - 'Recorder': 'adv_recorder.md'
  - 'Rendering options': 'adv_rendering_options.md'
  - 'Synchrony and time-step': 'adv_synchrony_timestep.md'
  - 'Traffic Manager': 'adv_traffic_manager.md'
- References:
  - 'Python API reference': 'python_api.md'
  - 'Code recipes': 'ref_code_recipes.md'
  - 'Blueprint Library': 'bp_library.md'
  - 'C++ reference' : 'ref_cpp.md'
  - 'Recorder binary file format': 'ref_recorder_binary_file_format.md'
  - "Sensors reference": 'ref_sensors.md'  
- ROS bridge:
  - 'ROS bridge installation': 'ros_installation.md'
  - 'CARLA messages reference': 'ros_msgs.md'
  - 'Launchfiles reference': 'ros_launchs.md'
- Tutorials (general):
  - 'Add friction triggers': "tuto_G_add_friction_triggers.md"
  - 'Control vehicle physics': "tuto_G_control_vehicle_physics.md"
  - 'Control walker skeletons': "tuto_G_control_walker_skeletons.md"
- Tutorials (assets):
  - 'Import new assets': 'tuto_A_import_assets.md'
  - 'Map creation': 'tuto_A_map_creation.md'
  - 'Map customization': 'tuto_A_map_customization.md'
  - 'Standalone asset packages': 'tuto_A_standalone_packages.md'
  - "Use Epic's Automotive materials": 'tuto_A_epic_automotive_materials.md'
  - 'Vehicle modelling': 'tuto_A_vehicle_modelling.md'
- Tutorials (developers):
  - 'Contribute with assets': 'tuto_D_contribute_assets.md'
  - 'Create a sensor': 'tuto_D_create_sensor.md'
  - 'Make a release': 'tuto_D_make_release.md'
  - 'Generate pedestrian navigation': 'tuto_D_generate_pedestrian_navigation.md'
- Contributing:
  - 'Contribution guidelines': 'cont_contribution_guidelines.md'
  - 'Code of conduct': 'cont_code_of_conduct.md'
  - 'Coding standard': 'cont_coding_standard.md'
  - 'Documentation standard': 'cont_doc_standard.md'

markdown_extensions:
  - admonition
