site_name: CARLA Simulator
repo_url: https://github.com/carla-simulator/carla
docs_dir: Docs
theme: readthedocs

nav:
- Home: 'index.md'
- Quick start:
  - 'Getting started': 'getting_started.md'
  - 'Python API tutorial': 'python_api_tutorial.md'
  - 'Configuring the simulation': 'configuring_the_simulation.md'
  - 'Cameras and sensors': 'cameras_and_sensors.md'
  - 'F.A.Q.': 'faq.md'
- Building from source:
  - 'How to build on Linux': 'how_to_build_on_linux.md'
  - 'How to build on Windows': 'how_to_build_on_windows.md'
- Advanced topics:
  - 'Python API reference': 'python_api.md'
  - 'Running without display and selecting GPUs': 'carla_headless.md'
  - 'Running in a Docker': 'carla_docker.md'
  - "How to make a new map with RoadRunner": 'how_to_make_a_new_map.md'
  - "How to link Epic's Automotive Materials": 'epic_automotive_materials.md'
  - "How to automatically generate a map from RoadRunner": 'generate_map_from_fbx.md'
  - "How to export and import maps to distribution builds": 'export_import_dist.md'
  - "How to add custom props to the Blueprint Library": 'define_custom_props.md'
- Contributing:
  - 'Contribution guidelines': 'CONTRIBUTING.md'
  - 'Coding standard': 'coding_standard.md'
  - 'Code of conduct': 'CODE_OF_CONDUCT.md'
- Development:
  - 'Map customization': 'map_customization.md'
  - 'Build system': 'build_system.md'
- Art guidelines:
  - 'How to add assets': 'how_to_add_assets.md'
  - 'How to model vehicles': 'how_to_model_vehicles.md'

markdown_extensions:
  - admonition
