site_name: CARLA Simulator
repo_url: https://github.com/carla-simulator/carla
docs_dir: Docs
edit_uri: 'edit/master/Docs/'
theme: readthedocs

nav:
- Home: 'index.md'
- Quick start:
  - 'Getting started': 'getting_started.md'
  - 'Python API tutorial': 'python_api_tutorial.md'
  - 'Configuring the simulation': 'configuring_the_simulation.md'
  - 'Cameras and sensors': 'cameras_and_sensors.md'
  - 'F.A.Q.': 'faq.md'
- Building from source:
  - 'How to build on Linux': 'how_to_build_on_linux.md'
  - 'How to build on Windows': 'how_to_build_on_windows.md'
- Advanced topics:
  - 'Python API reference': 'python_api.md'
  - 'Running without display and selecting GPUs': 'carla_headless.md'
  - 'Running in a Docker': 'carla_docker.md'
  - "How to make a new map with RoadRunner": 'how_to_make_a_new_map.md'
  - "How to link Epic's Automotive Materials": 'epic_automotive_materials.md'
  - "Creating standalone asset packages for distribution": 'asset_packages_for_dist.md'
  - "How to record and replay": 'recorder_and_playback.md'
  - "Recorder binary file format": 'recorder_binary_file_format.md'
  - "How to add friction triggers": "how_to_add_friction_triggers.md"
  - "How to control vehicle physics": "how_to_control_vehicle_physics.md"
  - "How to control walker skeletons": "walker_bone_control.md"
- Contributing:
  - 'Contribution guidelines': 'CONTRIBUTING.md'
  - 'Coding standard': 'coding_standard.md'
  - 'Code of conduct': 'CODE_OF_CONDUCT.md'
- Development:
  - 'Index': 'dev/index.md'
  - 'Map customization': 'dev/map_customization.md'
  - 'Build system': 'dev/build_system.md'
  - "How to upgrade content": 'dev/how_to_upgrade_content.md'
  - "How to make a release": 'dev/how_to_make_a_release.md'
- Art guidelines:
  - 'How to add assets': 'how_to_add_assets.md'
  - 'How to model vehicles': 'how_to_model_vehicles.md'

markdown_extensions:
  - admonition
