site_name: SUMMIT 
docs_dir: Docs
nav:
  - Home: index.md
  - Getting started:
    - Introduction: getting_started/introduction.md
    - Setting up SUMMIT: getting_started/setup.md
  - Tutorials:
    - Preparing maps: tutorials/preparing_maps.md
    - Spawning meshes: tutorials/spawning_meshes.md
    - Spawning imagery: tutorials/spawning_imagery.md
    - Simulating traffic: tutorials/simulating_traffic.md
  - References:
    - Python API reference: references/python_api.md
theme: readthedocs
