site_name: SUMMIT 
docs_dir: Docs
nav:
  - Home: index.md
  - Getting started:
    - Introduction: getting_started/introduction.md
    - Quick start: getting_started/quick_start.md
    - Building SUMMIT: getting_started/building.md
  - Tutorials:
    - Preparing maps: tutorials/preparing_maps.md
    - Loading and spawning maps: tutorials/loading_and_spawning_maps.md
    - Using roads and sidewalks: tutorials/using_roads_and_sidewalks.md
    - Simulating traffic: tutorials/simulating_traffic.md
  - References:
    - Python API reference: references/python_api.md
    - SUMMIT map library: references/summit_map_library.md
theme: readthedocs

markdown_extensions:
  - admonition
